#!/usr/bin/env bash
set -euo pipefail

# Start the AWS GPU instance, auto-update security group for home IP changes,
# poll vLLM health, and write .env.cloud with the new endpoint.
#
# Note: HTTP (not HTTPS) is used because vLLM does not serve TLS natively.
# Security group restricts to home IP + API key provides auth. TLS can be
# added later behind nginx if needed.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"

# Source .env if it exists (for INSTANCE_ID, VLLM_API_KEY, SG_ID)
if [[ -f "$PROJECT_DIR/.env" ]]; then
    set -a; source "$PROJECT_DIR/.env"; set +a
fi

INSTANCE_ID="${AWS_GPU_INSTANCE_ID:?Set AWS_GPU_INSTANCE_ID in .env}"
REGION="${AWS_GPU_REGION:-us-east-1}"
VLLM_API_KEY="${SEI_LLM_API_KEY:?Set SEI_LLM_API_KEY in .env}"
SG_ID="${AWS_GPU_SG_ID:?Set AWS_GPU_SG_ID in .env}"

# --- Auto-update security group for home IP changes ---
MY_IP=$(curl -s https://checkip.amazonaws.com)
echo "Current home IP: $MY_IP"

# Check if our IP is already authorized for SSH (port 22)
EXISTING_CIDRS=$(aws ec2 describe-security-groups \
    --group-ids "$SG_ID" \
    --region "$REGION" \
    --query 'SecurityGroups[0].IpPermissions[?FromPort==`22`].IpRanges[].CidrIp' \
    --output text 2>/dev/null || echo "")

if echo "$EXISTING_CIDRS" | grep -q "${MY_IP}/32"; then
    echo "Security group already allows $MY_IP -- no update needed."
else
    echo "Home IP not in security group. Updating rules..."
    # Revoke old /32 rules for ports 22 and 8000 (ignore errors if none exist)
    for OLD_CIDR in $EXISTING_CIDRS; do
        if [[ "$OLD_CIDR" == *"/32" ]]; then
            echo "  Revoking old SSH rule: $OLD_CIDR"
            aws ec2 revoke-security-group-ingress \
                --group-id "$SG_ID" \
                --protocol tcp --port 22 \
                --cidr "$OLD_CIDR" \
                --region "$REGION" 2>/dev/null || true
            echo "  Revoking old vLLM rule: $OLD_CIDR"
            aws ec2 revoke-security-group-ingress \
                --group-id "$SG_ID" \
                --protocol tcp --port 8000 \
                --cidr "$OLD_CIDR" \
                --region "$REGION" 2>/dev/null || true
        fi
    done

    # Authorize new IP for both ports
    aws ec2 authorize-security-group-ingress \
        --group-id "$SG_ID" \
        --protocol tcp --port 22 \
        --cidr "${MY_IP}/32" \
        --region "$REGION"
    aws ec2 authorize-security-group-ingress \
        --group-id "$SG_ID" \
        --protocol tcp --port 8000 \
        --cidr "${MY_IP}/32" \
        --region "$REGION"
    echo "Security group updated: SSH + vLLM now allow ${MY_IP}/32"
fi
# --- End SG update ---

echo "Starting GPU instance $INSTANCE_ID..."
aws ec2 start-instances --instance-ids "$INSTANCE_ID" --region "$REGION" >/dev/null

echo "Waiting for instance to be running..."
aws ec2 wait instance-running --instance-ids "$INSTANCE_ID" --region "$REGION"

PUBLIC_IP=$(aws ec2 describe-instances \
    --instance-ids "$INSTANCE_ID" \
    --region "$REGION" \
    --query 'Reservations[0].Instances[0].PublicIpAddress' \
    --output text)
echo "Public IP: $PUBLIC_IP"

echo "Waiting for vLLM health (model loading ~2-4 min)..."
for i in $(seq 1 60); do
    if curl -sf "http://${PUBLIC_IP}:8000/health" >/dev/null 2>&1; then
        echo "vLLM is healthy!"
        break
    fi
    if [[ $i -eq 60 ]]; then
        echo "ERROR: vLLM did not become healthy in 5 minutes."
        exit 1
    fi
    sleep 5
done

# Verify API-key auth
if ! curl -sf -H "Authorization: Bearer ${VLLM_API_KEY}" \
    "http://${PUBLIC_IP}:8000/v1/models" >/dev/null; then
    echo "WARNING: /v1/models did not respond with API key. Check vLLM logs."
fi

# Write .env.cloud so sei_engine (or sourcing scripts) can pick up the new values
cat > "$PROJECT_DIR/.env.cloud" <<ENVEOF
# Auto-generated by start_gpu.sh -- do not edit manually
SEI_LLM_URL=http://${PUBLIC_IP}:8000
SEI_LLM_API_KEY=${VLLM_API_KEY}
ENVEOF

echo ""
echo "=== GPU READY ==="
echo "SEI_LLM_URL=http://${PUBLIC_IP}:8000"
echo "SEI_LLM_API_KEY=${VLLM_API_KEY}"
echo ""
echo "To use with sei_engine, either:"
echo "  source ${PROJECT_DIR}/.env.cloud"
echo "  python scripts/sei_engine.py"
echo ""
echo "Or manually:"
echo "  export SEI_LLM_URL=http://${PUBLIC_IP}:8000"
echo "  export SEI_LLM_API_KEY=${VLLM_API_KEY}"
